version: "3.9"

services:
  backend_dev:
    image: my-bookshelfs_backend_dev:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development

  frontend_dev:
    image: my-bookshelfs_frontend_dev:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - backend_dev
