name: Unit Test Backend

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - staging
    paths:
      - ".backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Instalar dependências
        run: npm install
        working-directory: .backend

      - name: Executar testes
        run: npm test:unit
        working-directory: .backend
